name: Tests and checks on push

on:
  push:
    branches:
      - rewrite

jobs:
  run-checks-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prettier
        run: npm run prettier:check
      - name: Lint TS
        run: npm run lint:ts
      - name: Stylelint
        run: npm run lint:styles
      - name: Typecheck
        run: npm run typecheck
